// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzR5I3GvKuJJeT_1WBjHpZY5HqDwRgYxA',
    appId: '1:889326595310:web:f8f2dd5839a5b6931d97ff',
    messagingSenderId: '889326595310',
    projectId: 'jtm-dairyfarmapp',
    authDomain: 'jtm-dairyfarmapp.firebaseapp.com',
    storageBucket: 'jtm-dairyfarmapp.firebasestorage.app',
    measurementId: 'G-1DVLGJQ64C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJHpZvktt_OzlH-vw1R07xM7hkE596NVw',
    appId: '1:889326595310:android:26a88bca192e13791d97ff',
    messagingSenderId: '889326595310',
    projectId: 'jtm-dairyfarmapp',
    storageBucket: 'jtm-dairyfarmapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRDDgLdkZ6dcNnPJbdJq1OiEvtD0SJXFA',
    appId: '1:889326595310:ios:1520db77fadac7e81d97ff',
    messagingSenderId: '889326595310',
    projectId: 'jtm-dairyfarmapp',
    storageBucket: 'jtm-dairyfarmapp.firebasestorage.app',
    iosBundleId: 'com.example.dairyFarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRDDgLdkZ6dcNnPJbdJq1OiEvtD0SJXFA',
    appId: '1:889326595310:ios:1520db77fadac7e81d97ff',
    messagingSenderId: '889326595310',
    projectId: 'jtm-dairyfarmapp',
    storageBucket: 'jtm-dairyfarmapp.firebasestorage.app',
    iosBundleId: 'com.example.dairyFarmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzR5I3GvKuJJeT_1WBjHpZY5HqDwRgYxA',
    appId: '1:889326595310:web:98b74126a236350a1d97ff',
    messagingSenderId: '889326595310',
    projectId: 'jtm-dairyfarmapp',
    authDomain: 'jtm-dairyfarmapp.firebaseapp.com',
    storageBucket: 'jtm-dairyfarmapp.firebasestorage.app',
    measurementId: 'G-GSPXMPVRNW',
  );
}
